# Generated by Django 4.0.5 on 2022-07-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user_for_public',
            field=models.TextField(default=''),
        ),
    ]
